### ISSUE TITLE
TC9 - Minimum passwords of 0 characters can be saved.

### ISSUE THREAD

**Issue by KristiforMilchev** [KeysFortress/KF_Application#29]

**Comment by Tyler-Kuhn** [comment]
@KristiforMilchev 
### **TC9 - Minimum Password Length - PASSED**

**Environment:**  Android Studio
                       Pixel 8 Pro
                       Android 14
**Steps:**

1. Launch the Key Fortress application on Windows.
2. Press the "Generate Password" button to open the password generation window.
3. Enter a Name and Email.
4. Click on "Advanced Options".
5. Set the password length to the minimum (0)

**Expected Result:**
The application prevents saving a password with 0 length.

**Actual Result:**
The application prevents saving a password with 0 length.
